[project]
protostar-version = "0.13.0"
lib-path = "lib"

[contracts]
starkDefi = ["src"]
factory = ["contracts/dex/V1/factory/src"]
router = ["contracts/dex/V1/router/src"]
pair = ["contracts/dex/V1/pair/src"]


# Shared configration profile
[profile.devnet.project]
gateway-url = "http://127.0.0.1:5050/"
chain-id = 1536727068981429685321

[profile.testnet.project]
network = "testnet"