[package]
name = "starkDefi"
version = "1.0.0"

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = true

[dependencies]
starknet = ">=2.1.0-rc1"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.4.0" }


[tool.snforge]
# exit_first = true

[scripts]
# build = "protostar build"
test = "snforge"
devnet = "docker-compose up -d"
