[package]
name = "starkDefi"
version = "1.0.0"

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = true

[dependencies]
starknet = ">=2.1.1"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.4.1" }


[tool.snforge]
exit_first = true

[scripts]
devnet = "docker-compose up -d"

[tool.sncast.testnet]
name="testnet"
account = "./{path_to_account}.json"
keystore = "./{path_to_account_keystore}.json"
url = "{node_url}"

[tool.sncast.mainnet]
name="mainnet"
account = "./{path_to_account}.json"
keystore = "./{path_to_account_keystore}.json"
url = "{node_url}"