name: Run Test on PRs

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "0.6.2"

      # - name: Install Starknet-foundry
      #   uses: curl -L https://raw.githubusercontent.com/foundry-rs/starknet-foundry/master/scripts/install.sh | sh

      - name: Check formatting
        run: scarb fmt --check

      - name: Run Test
        run: scarb test
