name: Run Test on PRs

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Install Protostar
        uses: curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash

      - name: Add to GITHUB_PATH
        run: echo "/home/runner/.protostar/dist/protostar" >> $GITHUB_PATH

      - name: Install dependencies (Protostar)
        run: protostar install

      - name: Compile the contracts
        run: protostar build

      - name: Run Test
        run: protostar test
