name: Run Test on PRs

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Get Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "0.7.0"

      - name: check format
        run: scarb fmt --check

      - name: scar Test
        run: scarb test
