name: Run Test on PRs

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1.2.0
  
      - name: Check formatting
        run: scarb fmt --check

      - name: Run Test
        run: scarb test
